### PR TITLE
Set original qualifier in cancel/complete cases and simplify their preparing

### LINKED ISSUE #139: NPE on websocket gateway client
NPE:
```
java.lang.NullPointerException: null
	at io.scalecube.services.api.Qualifier.getQualifierNamespace(Qualifier.java:28) ~[scalecube-services-api-2.9.1-RC8.jar:?]
	at io.exberry.exchange.operation.gateway.GatewaySessionHandlerImpl.isOperationEvents(GatewaySessionHandlerImpl.java:151) ~[app.jar:?]
	at io.exberry.exchange.operation.gateway.GatewaySessionHandlerImpl.onResponse(GatewaySessionHandlerImpl.java:133) ~[app.jar:?]
	at io.scalecube.services.gateway.ws.WebsocketGatewaySession.lambda$send$3(WebsocketGatewaySession.java:104) ~[scalecube-services-gateway-netty-2.8.16-RC5.jar:?]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:189) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2317) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:103) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:171) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.5.RELEASE.jar:3.3.5.RELEASE]
	at reactor.core.publisher.MonoDefer
```

Presumably this is sig CANCEL and/or COMPLETE:  io.scalecube.services.gateway.ws.GatewayMessages#newCancelMessage 
 io.scalecube.services.gateway.ws.GatewayMessages#newCompleteMessage  those are two places where qualifier is explicitly not being set.

Proposed solution (@segabriel) -- store original request qualifier somewhere and when it's needed to send CANCEL and/or CANCEL  then  **use** that original saved somewhere message qualfier.

### PR DESCRIPTION
**Pull request by segabriel**
Closes #139

### CODE REVIEW

File: services-gateway-netty/src/main/java/io/scalecube/services/gateway/ws/GatewayMessages.java [hunk 1]
```diff
@@ -1,9 +1,7 @@
 package io.scalecube.services.gateway.ws;
 
 import io.scalecube.services.api.ServiceMessage;
-import io.scalecube.services.api.ServiceMessage.Builder;
 import io.scalecube.services.exceptions.DefaultErrorMapper;
-import java.util.Optional;
 
 final class GatewayMessages {
```
Comment (artem-v) [inline services-gateway-netty/src/main/java/io/scalecube/services/gateway/ws/GatewayMessages.java]: Plz make this class public and make it's static methods public (yes, you would have to write some javadoc, unfortunately). It was a mistake to make it package-private in this first place.

**Review by artem-v — APPROVED** [review]

File: services-gateway-netty/src/main/java/io/scalecube/services/gateway/ws/GatewayMessages.java (hunk 1 above)
Comment (segabriel) [reply services-gateway-netty/src/main/java/io/scalecube/services/gateway/ws/GatewayMessages.java]: Oh, it's a trap =)
